### ISSUE TITLE
Pressing enter crashes the game sometimes, need to add invalid input message instead of letting the game crash.

### ISSUE THREAD

**Issue by will-adamson** [Adamgm3/studio2-astrophobia#8]

**Comment by will-adamson** [comment]
Easiest to use switch statements with a default option.

**Comment by HugoSCode** [comment]
Done this for most cases but will have to edit some once user input is changed for consistency

**Comment by Walkcm7** [comment]
This is already fixed on main. Check which branch you're on, if you make a branch and other pull requests have been merged, your branch won't be updated with the changes.

**Comment by will-adamson** [comment]
This is an old issue. It has since been fixed.
